### ISSUE TITLE
PPT curriculum materials are corrupted

### ISSUE THREAD

**Issue by JerryChin** [gaoyifan/os-experiment#1]
Please check the integrity of the curriculum materials.

**Comment by gaoyifan** [comment]
Please provide the specific PDF link which is corrupted

**Comment by JerryChin** [comment]
See the following list:

1. [教学大纲](https://gaoyifan.github.io/os-experiment/ppt/syllabus.ppt)
2. [第一部分](https://gaoyifan.github.io/os-experiment/ppt/ch01_intro.ppt)
3. [第二部分](https://gaoyifan.github.io/os-experiment/ppt/ch01_intro_2.ppt)

**Comment by JerryChin** [comment]
I've asked my colleagues to open the above files, but failed to reproduce the problem, it may have something to do with my office suite.

I'm using Microsoft Office 2013, version 15.0.4420.1017.

I will close this issue as it seems not a big impact on the majority.
